server:
  port: 40008

spring:
  application:
    name: orange-security
  datasource:
    username: root
    password: 123456Abcd
    url: jdbc:mysql://orange-mysql/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: true
    prefix: classpath:/templates/
    suffix: .html
eureka:
  instance:
    hostname: orange-security
    prefer-ip-address: true
    ip-address: 193.112.143.164
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://orange-server:40000/eureka/
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.security.pojo
