server:
  port: 40000
spring:
  application:
    name: orange-server
eureka:
  instance:
    hostname: orange-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://orange-server:40000/eureka/